# PostgreSQL config
# Secret created dynamically from GitHub Secrets in CI/CD
# For local: kubectl create secret generic postgres-secret -n devops-demo ...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: devops-demo
  labels:
    app: postgres
data:
  PGDATA: /var/lib/postgresql/data/pgdata
